apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-alerts.yaml
  - monitoring-dashboards.yaml
  - monitoring-loki-config.yaml
  - monitoring-tempo-config.yaml
  - monitoring-tls.yaml
