apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: admin
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: cluster/grafana
        property: admin_password
