apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
    template:
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .oidcClientSecret }}"
  data:
    - secretKey: oidcClientSecret
      remoteRef:
        key: cluster/grafana
        property: oidc_client_secret
