apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: grafana-db-credentials
    creationPolicy: Owner
    template:
      data:
        GF_DATABASE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: cluster/grafana
        property: db_password
